# Generated by Django 4.0.3 on 2022-05-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_info',
            field=models.CharField(default='boulevard sanmartin al fondo', max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(default='9:30', max_length=250),
        ),
    ]
