# Generated by Django 4.0.3 on 2022-04-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default=334327, max_length=250, unique=True),
        ),
    ]
