# Generated by Django 4.0.3 on 2022-04-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_food_description_alter_food_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='price_total',
        ),
        migrations.AddField(
            model_name='food',
            name='slug',
            field=models.SlugField(default=292130, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default=347596, max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(default=359386, max_length=100, unique=True),
        ),
    ]
