# Generated by Django 4.0.3 on 2022-04-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_name_alter_order_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered',
            new_name='complete',
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default=266315, max_length=250, unique=True),
        ),
    ]
