# Generated by Django 4.0.3 on 2022-04-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_price_orderitem_price_total_food_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='order',
            name='slug',
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default=376391, max_length=250, unique=True),
        ),
    ]
